config_version : 0

name: lsync

version: 0.0.0

uuid: 25ac67cf-1b0f-47e8-8d84-9216b38a1436

authors:
- vanaarde

description: >
  lsync is a collaborative cloud storage synchronisation utility

requires:
- python

help: $BROWSER file://!ROOT!/doc/html/index.html

tools:
- lsync

commands:
- export PATH=$PATH:!ROOT!/bin
- export PYTHONPATH=$PYTHONPATH:!ROOT!/python

